- name: Configure RHEL
  hosts: all
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: Copy ssh keys
      authorized_key:
        user: "{{ rhel.user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    - name: Modify sudo config to allow openshift users sudo without a password
      lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'
    - name: Register as user and password using a given pool id
      redhat_subscription:
        state: present
        username: "{{ rh_subscription.username }}"
        password: "{{ rh_subscription.password }}"
        pool_ids: "{{ rh_subscription.poolid }}"
    - name: Ensure EPEL is enabled
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: Upgrade all the packages
      yum:
        name: '*'
        state: latest
        